/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up a new tenant and its first admin user.
         * @description Creates a new tenant, provisions its isolated database (schema + seed defaults), and creates the first admin user. Returns an access token for the new admin. This is a control-plane operation.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in to a tenant.
         * @description Authenticates a user within a specific tenant (identified by slug, since email is unique only per tenant) and returns an access token. This is a control-plane operation.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently authenticated user.
         * @description Returns the authenticated user and their tenant, resolved from the bearer token. Requires authentication.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List departments.
         * @description Returns all departments for the tenant. Org hierarchy is expressed via each department's nullable parent_id.
         */
        get: operations["listDepartments"];
        put?: never;
        /** Create a department. */
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get a department by id. */
        get: operations["getDepartment"];
        put?: never;
        post?: never;
        /** Delete a department. */
        delete: operations["deleteDepartment"];
        options?: never;
        head?: never;
        /** Update a department. */
        patch: operations["updateDepartment"];
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List employees.
         * @description Returns the tenant's employees, optionally filtered by department or status.
         */
        get: operations["listEmployees"];
        put?: never;
        /** Create an employee. */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get an employee by id. */
        get: operations["getEmployee"];
        put?: never;
        post?: never;
        /** Delete an employee. */
        delete: operations["deleteEmployee"];
        options?: never;
        head?: never;
        /** Update an employee. */
        patch: operations["updateEmployee"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles.
         * @description Returns the tenant's roles. Each role carries a set of permission keys (not yet enforced in v1).
         */
        get: operations["listRoles"];
        put?: never;
        /** Create a role. */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get a role by id. */
        get: operations["getRole"];
        put?: never;
        post?: never;
        /**
         * Delete a role.
         * @description Deletes a role. Employees assigned to it have their role cleared (set to null).
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /** Update a role. */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations. */
        get: operations["listLocations"];
        put?: never;
        /** Create a location. */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get a location by id. */
        get: operations["getLocation"];
        put?: never;
        post?: never;
        /**
         * Delete a location.
         * @description Deletes a location. Shifts at it have their location cleared (set to null).
         */
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        /** Update a location. */
        patch: operations["updateLocation"];
        trace?: never;
    };
    "/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List shifts.
         * @description Lists shifts, optionally filtered by employee, status, and a [from, to) window on the shift start time.
         */
        get: operations["listShifts"];
        put?: never;
        /** Create a shift (starts as a draft). */
        post: operations["createShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Get a shift by id. */
        get: operations["getShift"];
        put?: never;
        post?: never;
        /** Delete a shift. */
        delete: operations["deleteShift"];
        options?: never;
        head?: never;
        /**
         * Update a shift.
         * @description Updates shift fields. Status transitions go through the publish endpoint, not here.
         */
        patch: operations["updateShift"];
        trace?: never;
    };
    "/shifts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a shift.
         * @description Transitions a shift to published, making it visible to the assigned staff. Idempotent.
         */
        post: operations["publishShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/login": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision a login for an employee.
         * @description Creates a control-plane user account for the employee and links it (employees.user_id), so the employee can authenticate (e.g. field staff on the mobile app). Fails if the employee already has a login or the email is already taken in this tenant.
         */
        post: operations["createEmployeeLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List attendance records.
         * @description Lists attendance records, optionally filtered by employee, status, and a [from, to) window on check-in time.
         */
        get: operations["listAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in (field staff).
         * @description Records a check-in for the authenticated employee (resolved from the token). Idempotent on client_id: replaying the same client_id returns the existing record rather than creating a duplicate — this is what makes the offline mobile queue safe to replay.
         */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out (field staff).
         * @description Records check-out against an existing attendance record identified by the same client_id used at check-in. Idempotent.
         */
        post: operations["checkOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated employee's own shifts.
         * @description Field-facing: returns shifts for the employee linked to the caller's login (resolved from the token), optionally filtered by status and a [from, to) window on start time. Returns an empty list if the caller has no linked employee record.
         */
        get: operations["listMyShifts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manager live view — who is working now.
         * @description Published shifts whose start time falls in the window, each joined with the employee and their current attendance state. The window defaults to the current UTC day; clients should pass from/to computed in the user's local timezone for correct day boundaries (the server has no tenant timezone). Shifts that started before the window (e.g. overnight) are not included — the filter is on shift start time.
         */
        get: operations["getLiveView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description A stable, machine-readable error code.
             * @example invalid_credentials
             */
            code: string;
            /** @description A human-readable explanation. */
            message: string;
        };
        SignupRequest: {
            /** @example Saigon Tours Co. */
            company_name: string;
            /**
             * @description URL/login-friendly tenant identifier. If omitted, derived from the company name. Lowercase letters, digits, and hyphens.
             * @example saigon-tours
             */
            slug?: string;
            /** @description Optional. Reserved for M2, when it will seed the admin's employee profile in the tenant database. Accepted but not yet persisted. */
            admin_full_name?: string;
            /** Format: email */
            admin_email: string;
            /** Format: password */
            admin_password: string;
        };
        LoginRequest: {
            /** @example saigon-tours */
            tenant_slug: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            /** @description JWT access token. */
            token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["UserSummary"];
            tenant: components["schemas"]["TenantSummary"];
        };
        CurrentUserResponse: {
            user: components["schemas"]["UserSummary"];
            tenant: components["schemas"]["TenantSummary"];
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "manager" | "employee";
            /** @enum {string} */
            status: "active" | "disabled";
        };
        TenantSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            status: "active" | "suspended" | "provisioning";
            plan: string;
        };
        Department: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateDepartmentRequest: {
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        /** @description PATCH semantics — only provided fields are changed. Fields cannot be cleared back to null via PATCH in v1 (omitting a field and sending null are equivalent). */
        UpdateDepartmentRequest: {
            name?: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        Role: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @description Permission keys granted by this role. Stored but not enforced in v1. */
            permissions: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateRoleRequest: {
            name: string;
            description?: string | null;
            permissions?: string[];
        };
        /** @description PATCH semantics — only provided fields are changed. permissions, when provided, replaces the whole set. */
        UpdateRoleRequest: {
            name?: string;
            description?: string | null;
            permissions?: string[];
        };
        Employee: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Links to the control-plane users.id (different database; no FK).
             */
            user_id?: string | null;
            /**
             * Format: uuid
             * @description The employee's assigned role (access-control), if any.
             */
            role_id?: string | null;
            full_name: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** @enum {string} */
            employment_type: "full_time" | "part_time" | "freelance" | "seasonal";
            /** Format: uuid */
            department_id?: string | null;
            title?: string | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date */
            hired_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateEmployeeRequest: {
            full_name: string;
            /** @enum {string} */
            employment_type: "full_time" | "part_time" | "freelance" | "seasonal";
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            title?: string | null;
            /** Format: date */
            hired_at?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            /** Format: uuid */
            role_id?: string | null;
            /**
             * @description Optional on create; defaults to active.
             * @enum {string}
             */
            status?: "active" | "inactive";
        };
        /** @description PATCH semantics — only provided fields are changed. Fields cannot be cleared back to null via PATCH in v1 (omitting a field and sending null are equivalent). */
        UpdateEmployeeRequest: {
            full_name?: string;
            /** @enum {string} */
            employment_type?: "full_time" | "part_time" | "freelance" | "seasonal";
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            title?: string | null;
            /** Format: date */
            hired_at?: string | null;
            /** Format: uuid */
            role_id?: string | null;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        Location: {
            /** Format: uuid */
            id: string;
            name: string;
            address?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateLocationRequest: {
            name: string;
            address?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
        };
        /** @description PATCH semantics — only provided fields are changed; fields cannot be cleared to null in v1. */
        UpdateLocationRequest: {
            name?: string;
            address?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
        };
        Shift: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employee_id: string;
            /** Format: uuid */
            location_id?: string | null;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            notes?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateShiftRequest: {
            /** Format: uuid */
            employee_id: string;
            /** Format: uuid */
            location_id?: string | null;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            notes?: string | null;
        };
        /** @description PATCH semantics — only provided fields are changed; fields cannot be cleared to null in v1. Status transitions go through POST /shifts/{id}/publish. */
        UpdateShiftRequest: {
            /** Format: uuid */
            employee_id?: string;
            /** Format: uuid */
            location_id?: string | null;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            notes?: string | null;
        };
        CreateLoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @description Defaults to employee when omitted.
             * @enum {string}
             */
            role?: "admin" | "manager" | "employee";
        };
        AttendanceRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employee_id: string;
            /** Format: uuid */
            shift_id?: string | null;
            /**
             * Format: uuid
             * @description Client-generated id; the idempotency key for check-in/out.
             */
            client_id: string;
            /** Format: date-time */
            check_in_at?: string | null;
            /** Format: double */
            check_in_lat?: number | null;
            /** Format: double */
            check_in_lng?: number | null;
            check_in_photo_url?: string | null;
            /** Format: date-time */
            check_out_at?: string | null;
            /** Format: double */
            check_out_lat?: number | null;
            /** Format: double */
            check_out_lng?: number | null;
            check_out_photo_url?: string | null;
            /** @enum {string} */
            status: "checked_in" | "checked_out" | "missed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CheckInRequest: {
            /**
             * Format: uuid
             * @description Client-generated idempotency key (stable across offline retries).
             */
            client_id: string;
            /** Format: uuid */
            shift_id?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            photo_url?: string | null;
        };
        CheckOutRequest: {
            /**
             * Format: uuid
             * @description The same client_id used at check-in.
             */
            client_id: string;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            photo_url?: string | null;
        };
        LiveViewEntry: {
            /** Format: uuid */
            employee_id: string;
            employee_name: string;
            shift: components["schemas"]["Shift"];
            /**
             * @description Derived state for this shift: not_checked_in (no attendance record linked), checked_in, or checked_out.
             * @enum {string}
             */
            attendance_status: "not_checked_in" | "checked_in" | "checked_out";
            /** Format: date-time */
            check_in_at?: string | null;
            /** Format: date-time */
            check_out_at?: string | null;
        };
    };
    responses: {
        /** @description The request was malformed or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication failed or is missing. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Tenant and admin user created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description A tenant with this slug, or admin email, already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user and tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's departments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Department created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The department. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Updated department. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEmployees: {
        parameters: {
            query?: {
                department_id?: string;
                status?: "active" | "inactive";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's employees. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Updated employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Role created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description A role with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's locations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Location created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The location. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description Updated location. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listShifts: {
        parameters: {
            query?: {
                employee_id?: string;
                status?: "draft" | "published";
                /** @description Inclusive lower bound on starts_at (ISO-8601). */
                from?: string;
                /** @description Exclusive upper bound on starts_at (ISO-8601). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching shifts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createShift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShiftRequest"];
            };
        };
        responses: {
            /** @description Shift created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The shift. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShiftRequest"];
            };
        };
        responses: {
            /** @description Updated shift. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    publishShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published shift. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createEmployeeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoginRequest"];
            };
        };
        responses: {
            /** @description Login created and linked to the employee. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The employee already has a login, or the email is taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAttendance: {
        parameters: {
            query?: {
                employee_id?: string;
                status?: "checked_in" | "checked_out" | "missed";
                /** @description Inclusive lower bound on check_in_at (ISO-8601). */
                from?: string;
                /** @description Exclusive upper bound on check_in_at (ISO-8601). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching attendance records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description Existing record returned (idempotent replay). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
            /** @description Checked in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The client_id is already in use by another employee. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    checkOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckOutRequest"];
            };
        };
        responses: {
            /** @description Checked out (or already checked out — idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMyShifts: {
        parameters: {
            query?: {
                status?: "draft" | "published";
                /** @description Inclusive lower bound on starts_at (ISO-8601). */
                from?: string;
                /** @description Exclusive upper bound on starts_at (ISO-8601). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's shifts, ordered by start time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLiveView: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound on shift starts_at (ISO-8601). Defaults to start of the current UTC day. */
                from?: string;
                /** @description Exclusive upper bound on shift starts_at (ISO-8601). Defaults to start of the next UTC day. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live view entries, ordered by shift start time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveViewEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
